[config] CLI command configure interface ip doesn't check correctness of inputs
sonic-net/sonic-utilities pull request #1381
Opened 2021-01-24 09:25 UTC by d-dashkov

**- What I did**
Before writing the settings to the database, check the correctness of the entries. 
If you try to bind the ip of a non-existent entry, show an error.
fixes https://github.com/Azure/sonic-buildimage/issues/6358

**- How I did it**
Added functions that check if an entry from an argument exists in the database.

**- How to verify it**
Try to configure ip to non-existent entry(Ethernet, Vlan, PortChannel, Loopback):
$ config interface ip add Ethernet0.5 10.0.0.1/24
$ config interface ip add Vlan4095 10.0.0.1/24

**- New command output (if the output of a command-line utility has changed)**
Error: 'interface_name' is not valid. Valid names [Ethernet/PortChannel/Vlan/Loopback]

2021-06-14 12:27 UTC, dprital commented
@d-dashkov  - Are you going to handle this PR ? I see that it got a conflict.

2021-06-17 19:04 UTC, dprital commented
> @d-dashkov - Are you going to handle this PR ? I see that it got a conflict.

@d-dashkov  ?

2021-06-17 19:15 UTC, d-dashkov commented
> > @d-dashkov - Are you going to handle this PR ? I see that it got a conflict.
> 
> @d-dashkov ?

Sorry, I will resolve conflicts within a couple of days

2021-06-22 05:10 UTC, liat-grozovik commented
/azp run

2021-10-06 07:42 UTC, liat-grozovik commented
@dgsudharsan could you please review this PR?

2021-10-06 23:23 UTC, prsunny reviewed
Changes lgtm, please add some unit-tests

2021-10-07 02:30 UTC, dgsudharsan requested changes
Please add UT. Please also sync to the latest

2021-10-09 18:03 UTC, dgsudharsan approved these changes, later dismissed

2021-10-12 02:33 UTC, prsunny approved these changes, later dismissed

2021-10-12 02:34 UTC, prsunny commented
/azp run

2021-12-30 12:30 UTC, d-dashkov commented
@dgsudharsan, I have fixed sonic-utilities tests and merge conflicts, but there are errors in pipeline which are not related to my changes, and it is about warm-reboot

2022-01-08 04:37 UTC, dgsudharsan approved these changes

2026-09-22 07:20 UTC, closed without merging