[ACL] Rollback the code of #1475 "Expand VLAN into VLAN members..."
sonic-net/sonic-utilities pull request #1775
Opened 2021-08-20 07:43 UTC by ezio-chen

#### What I did
For the issue of https://github.com/Azure/sonic-utilities/issues/1753, it shall not expand the VLAN to VLAN member ports.
Also modify the unit test because the behavior is changed.

#### How I did it
Remove the code for expand VLAN to VLAN member, just set the VLAN interface on ACL table.

#### How to verify it
Pass the unit test

#### Previous command output (if the output of a command-line utility has changed)
```
admin@sonic:~$ show vlan br
+-----------+--------------+-----------+----------------+-----------------------+-------------+
|   VLAN ID | IP Address   | Ports     | Port Tagging   | DHCP Helper Address   | Proxy ARP   |
+===========+==============+===========+================+=======================+=============+
|       100 |              | Ethernet0 | tagged         |                       | disabled    |
+-----------+--------------+-----------+----------------+-----------------------+-------------+
admin@sonic:~$ sudo config acl add table L3_TABLE L3 -p Vlan100
admin@sonic:~$ show acl table
Name      Type    Binding    Description    Stage
--------  ------  ---------  -------------  -------
L3_TABLE  L3      Ethernet0  L3_TABLE       ingress
admin@sonic:~$

```
#### New command output (if the output of a command-line utility has changed)
```
admin@sonic:~$ show vlan br
+-----------+--------------+-----------+----------------+-----------------------+-------------+
|   VLAN ID | IP Address   | Ports     | Port Tagging   | DHCP Helper Address   | Proxy ARP   |
+===========+==============+===========+================+=======================+=============+
|       100 |              | Ethernet0 | tagged         |                       | disabled    |
+-----------+--------------+-----------+----------------+-----------------------+-------------+
admin@sonic:~$ sudo config acl add table L3_TABLE L3 -p Vlan100
admin@sonic:~$ show acl table
Name      Type    Binding    Description    Stage
--------  ------  ---------  -------------  -------
L3_TABLE  L3      Vlan100    L3_TABLE       ingress
admin@sonic:~$

```

2021-08-20 18:35 UTC, prsunny reviewed
Why remove the code? Not all platforms may support Vlan bind. So suggest adding an option in CLI to use vlan binding. If the option is not specified, let it expand as it is done currently. @qiluo-msft , @bingwang-ms , what do you think?

2021-08-22 12:42 UTC, bingwang-ms commented
> Why remove the code? Not all platforms may support Vlan bind. So suggest adding an option in CLI to use vlan binding. If the option is not specified, let it expand as it is done currently. @qiluo-msft , @bingwang-ms , what do you think?

Agree. The Vlan expland feature is required in some scenarios. Please consider add an option to disable this behavior.

2021-08-23 00:15 UTC, ezio-chen commented
I still think this change is unreasonable, if a port join multiple VLAN, the ACL will affect to all VLANs on these ports.

For example, Ethernet0,Ethernet1 is the member of VLAN100 and VLAN200,
and you use the command to create the ACL
 ```sudo config acl add table Vlan100_ACL L3 -p Vlan100```
but the rules in Vlan100_ACL  will affect all traffic in Vlan200.

Why user just use  ```sudo config acl add table Vlan100_ACL L3 -p Ethernet0,Ethernet1 ``` to create ACL table if they really want to bind the ACL on these ports ?

2021-08-25 12:21 UTC, qiluo-msft commented
Thanks @ezio-chen for the contribution!
I agree current implementation is not perfect. We introduce this feature to temporarily enable some use case on Mellanox SN2700 platform, which does not support vlan acl binding.

I agree we should remove this feature in long term. To prevent sudden feature broken in short term, could you keep the behavior for Mellanox ASIC platforms and only change the behavior for all others?

2021-08-25 12:37 UTC, qiluo-msft requested changes
As comment

2021-09-06 10:08 UTC, ezio-chen commented
OK, and for this modification, can you please give some suggestions? 

Method 1: Distinguishing the HWSKU type internal, only expland VLAN on Mellanox.
Method 2: Add CLI options, e.g., config acl add table <table_name> <table_type> [ --expland-vlan ]
or other good ideas  ?

2021-09-07 07:53 UTC, qiluo-msft commented
Method 1 looks good to me.

2025-03-26 06:13 UTC, closed without merging