[voq] Add fabric counter cli commands
sonic-net/sonic-utilities pull request #1860
Opened 2021-10-06 18:27 UTC by mlorrillere

Add fabric counters CLI commands.

Commands are:
show fabric counters port
show fabric counters port -n asic4
show fabric counters port -n asic5 -e
show fabric counters queue
show fabric counters queue -n asic4

Signed-off-by: Maxime Lorrillere <mlorrillere@arista.com>

#### New command output (if the output of a command-line utility has changed)

```console
# fabricstat -h
usage: fabricstat [-h] [-q] [-n NAMESPACE] [-e]

Display the fabric port state and counters

optional arguments:
  -h, --help            show this help message and exit
  -q, --queue           Display fabric queue stat, otherwise port stat
  -n NAMESPACE, --namespace NAMESPACE
                        Display fabric ports for specific namespace
  -e, --errors          Display errors

Examples:
    fabricstat
    fabricstat --namespace asic0
    fabricstat -p -n asic0 -e
    fabricstat -q
    fabricstat -q -n asic0
```

```console
# show fabric counters -h
Usage: show fabric counters [OPTIONS] COMMAND [ARGS]...

  Show fabric port counters

Options:
  -h, -?, --help  Show this message and exit.

Commands:
  port   Show fabric port stat
  queue  Show fabric queue stat
```

```console
# show fabric counters port -h
Usage: show fabric counters port [OPTIONS]

  Show fabric port stat

Options:
  -d, --display [all|frontend]    Show internal interfaces  [default:
                                  frontend]
  -n, --namespace [asic0|asic1|asic2|asic3|asic4|asic5|asic6|asic7|asic8|asic9|asic10|asic11]
                                  Namespace name or all
  -e, --errors
  -h, -?, --help                  Show this message and exit.
```

Example output:
```console
# show fabric counters port -n asic0
  ASIC    PORT    STATE    IN_CELL    IN_OCTET    OUT_CELL    OUT_OCTET    CRC    FEC_CORRECTABLE    FEC_UNCORRECTABLE    SYMBOL_ERR
------  ------  -------  ---------  ----------  ----------  -----------  -----  -----------------  -------------------  ------------
     0       0     down          0           0           0            0      0             206318           7949306448             0
     0       1     down          0           0           0            0      0                  0           7949048925             0
     0       2     down          0           0           0            0      0                  0           7948552578             0
     0       3     down          0           0           0            0      0                  0           7948049934             0
     0       4     down          0           0           0            0      0                  0           7947524845             0
     0       5     down          0           0           0            0      0                  0           7946976870             0
     0       6     down          0           0           0            0      0                  0           7946408318             0
     0       7     down          0           0           0            0      0                  0           7945775522             0
[...]
     0     187     down          0           0           0            0   3024         6887370202              3773897   11545823075
     0     188     down          0           0           0            0      0                  0          13130704211             0
     0     189     down          0           0           0            0      0             118941          13129730022             0
     0     190       up          0           0           0            0    514          162556197           2717957083          4823
     0     191     down          0           0           0            0      0                  0          13128089835             0
```

2021-10-20 17:28 UTC, rlhui commented
@skeesara-nokia, @vganesan-nokia - please help review, thanks

2021-11-11 15:19 UTC, arlakshm requested changes

2021-11-11 15:19 UTC, arlakshm commented on scripts/fabricstat
> +FABRIC_PORT_STATUS_FIELD = "STATUS"
Can we add some unit tests for this?

2021-11-11 15:19 UTC, arlakshm commented on scripts/fabricstat
> +        asic = int(self.namespace[len(ASIC_NAME_PREFIX):])
We can use this function defined in sonic_py_common
[`get_asic_id_from_name(asic_name):` ](https://github.com/Azure/sonic-buildimage/blob/935923b8059a48b01a4daa765cdfa4bb6560562a/src/sonic-py-common/sonic_py_common/multi_asic.py#L136)

2021-11-25 00:49 UTC, mlorrillere commented on scripts/fabricstat
> +FABRIC_PORT_STATUS_FIELD = "STATUS"
Added unit test.

2021-12-14 20:17 UTC, arlakshm commented
> This pull request **introduces 9 alerts** when merging [c8cc5c7](https://github.com/Azure/sonic-utilities/commit/c8cc5c78c9aaef24e7fe087894e99ed04937a59a) into [c05845d](https://github.com/Azure/sonic-utilities/commit/c05845df1567c6d14312bb36f35c72c7ea6a93ee) - [view on LGTM.com](https://lgtm.com/projects/g/Azure/sonic-utilities/rev/pr-9e3a97535f012ecb305c9d18804a0043304d989c)
> 
> **new alerts:**
> 
> * 8 for Unused import
> * 1 for Unused local variable

@mlorrillere can you fix the lgtm alerts?

2021-12-14 20:21 UTC, arlakshm commented
> This pull request **introduces 9 alerts** when merging [c8cc5c7](https://github.com/Azure/sonic-utilities/commit/c8cc5c78c9aaef24e7fe087894e99ed04937a59a) into [c05845d](https://github.com/Azure/sonic-utilities/commit/c05845df1567c6d14312bb36f35c72c7ea6a93ee) - [view on LGTM.com](https://lgtm.com/projects/g/Azure/sonic-utilities/rev/pr-9e3a97535f012ecb305c9d18804a0043304d989c)
> 
> **new alerts:**
> 
> * 8 for Unused import
> * 1 for Unused local variable

@mlorrillere can you fix the lgtm alerts?

2021-12-14 21:40 UTC, mlorrillere commented
> > This pull request **introduces 9 alerts** when merging [c8cc5c7](https://github.com/Azure/sonic-utilities/commit/c8cc5c78c9aaef24e7fe087894e99ed04937a59a) into [c05845d](https://github.com/Azure/sonic-utilities/commit/c05845df1567c6d14312bb36f35c72c7ea6a93ee) - [view on LGTM.com](https://lgtm.com/projects/g/Azure/sonic-utilities/rev/pr-9e3a97535f012ecb305c9d18804a0043304d989c)
> > **new alerts:**
> > 
> > * 8 for Unused import
> > * 1 for Unused local variable
> 
> @mlorrillere can you fix the lgtm alerts?

My bad, I had the changes ready and forgot to commit. Should be fixed now.

2022-05-04 19:41 UTC, arlakshm commented
Hi @mlorrillere, the unit tests added for the fabric counter, `tests/fabricstat_test.py`,  are failing.
I think the reason they are failing is because the tests are trying to connect to the actual redis instance iso for mock db.
the script `fabricstat` the mock db must if the `UTILITIES_UNIT_TESTING` enivornment variable is set.

Please refer to this block as an example https://github.com/Azure/sonic-utilities/blob/master/scripts/intfutil#L15-L28

2022-06-21 18:49 UTC, mlorrillere commented
Hi @arlakshm 

I've addressed the remaining issues and all checks passed.

2022-08-02 21:32 UTC, mlorrillere commented
/easycla

2022-09-10 00:03 UTC, arlakshm commented
/Azp run Azure.sonic-utilities

2022-09-12 19:59 UTC, arlakshm approved these changes

2022-10-17 18:39 UTC, kenneth-arista commented
@arlakshm since everything is approved, can you merge this PR?

2022-10-17 20:35 UTC, merged