[show] vnet advertised-route [ip/ipv6] command
sonic-net/sonic-utilities pull request #2390
Opened 2022-09-20 19:53 UTC by siqbal1986

implementation and tests for "show vnet advertised-routes ip/ipv6 [string]"
#### What I did
Added a new show command to see the VNET Tunnel routes being advertised by BGP. THe output can be filtered based on IPv4/Ipv6 and community string.
#### How I did it
Iterate over the BGP_PROFILE_TABLE in Application DB and ADVERTISE_NETWORK_TABLE in state DB. Correlate the information and filter based on community string.
#### How to verify it
run **show vnet advertised-routes ip** or **show vnet advertised-routes ipv6** with optional community string.
```
$ show vnet advertised-route ip
Prefix           Profile              Community Id
---------------  -------------------  --------------
160.62.191.1/32  FROM_SDN_SLB_ROUTES  1234:1235
160.63.191.1/32  FROM_SDN_SLB_ROUTES  1234:1235
160.64.191.1/32  FROM_SDN_SLB_ROUTES  1234:1235

$ show vnet advertised-route ip 1234:1235
Prefix           Profile              Community Id
---------------  -------------------  --------------
160.62.191.1/32  FROM_SDN_SLB_ROUTES  1234:1235
160.63.191.1/32  FROM_SDN_SLB_ROUTES  1234:1235
160.64.191.1/32  FROM_SDN_SLB_ROUTES  1234:1235

$ show vnet advertised-route ipv6
Prefix                    Profile              Community Id
------------------------  -------------------  --------------
fddd:a150:a251::a6:1/128  FROM_SDN_SLB_ROUTES  1234:1235

$ show vnet advertised-route ipv6 1234:1235
Prefix                    Profile              Community Id
------------------------  -------------------  --------------
fddd:a150:a251::a6:1/128  FROM_SDN_SLB_ROUTES  1234:1235

```

#### Previous command output (if the output of a command-line utility has changed)
None
#### New command output (if the output of a command-line utility has changed)
NA

2022-09-30 00:40 UTC, prsunny approved these changes

2022-09-30 00:42 UTC, prsunny commented on show/vnet.py
> +    """Show vnet advertised-routes ip [community string XXXX:XXXX]"""
i recommend 'show vnet advertised-routes' and use '-6' for v6. 'ip' at the end confuses if we need to provide a parameter.

2022-09-30 00:44 UTC, prsunny requested changes

2022-09-30 00:44 UTC, prsunny commented on tests/mock_tables/state_db.json
> +    "ADVERTISE_NETWORK_TABLE|fddd:a150:a251::a6:1/128": {
please also add a case for no-profile

2022-09-30 00:46 UTC, siqbal1986 commented on tests/mock_tables/state_db.json
> +    "ADVERTISE_NETWORK_TABLE|fddd:a150:a251::a6:1/128": {
sure

2022-10-05 18:17 UTC, prsunny approved these changes

2022-10-05 23:11 UTC, prsunny approved these changes

2022-10-10 18:15 UTC, merged

2022-10-25 20:58 UTC, yxieca commented
@siqbal1986 this change cannot be cherry-picked to 202205 branch cleanly. Please raise separate PR.

2022-10-25 20:59 UTC, yxieca commented
@siqbal1986 this change cannot be cherry-picked to 202205 branch cleanly. Please raise separate PR.