Fix for show vxlan tunnel command display issue #11902
sonic-net/sonic-utilities pull request #2391
Opened 2022-09-20 20:20 UTC by skbhava

Issue:
Only one vni to vlan map entry in the output of show vxlan tunnel command
Fix:
Added fix to display all vni to vlan map entries for "show vxlan tunnel" and "show vxlan name commands.
Fixes #11902

2022-09-23 22:00 UTC, prsunny commented
Please provide the output of previous and new command. Please follow the template while creating PR

2022-09-28 04:43 UTC, dgsudharsan requested changes
Please add UT for coverage

2022-09-28 21:51 UTC, skbhava commented
> Please add UT for coverage

Added UT cases

2022-09-29 01:12 UTC, dgsudharsan approved these changes

2022-09-30 15:53 UTC, prsunny approved these changes

2022-09-30 15:53 UTC, merged