Issue#2583 : Fix for VXLAN tunnel port FDBs not displayed in 'show mac'
sonic-net/sonic-utilities pull request #2584
Opened 2023-01-06 09:39 UTC by praveenraja1

#### What I did

The 'fdbshow' script did not have the logic to check and use 'SAI_FDB_ENTRY_ATTR_ENDPOINT_IP' which used for FDB entries learnt on tunnel port, it tried to look up 'br_port_id' from oid_map which was failing.
Added logic to use 'SAI_FDB_ENTRY_ATTR_ENDPOINT_IP' for vxlan tunnel entries and fallback to the port_id lookup for normal fdb thats leant on ports.
Tested with a combination of VXLAN tunnel and normal port macs.

#### How I did it

Added logic to logic to look for 'SAI_FDB_ENTRY_ATTR_ENDPOINT_IP' in the ASIC_DB entry and use it for 'if_name ' , if it doesnt exists then legacy code flow is maintained. 

#### How to verify it

https://github.com/sonic-net/sonic-utilities/issues/2583

Has been raised for this. 

'show mac' with VXLAN tunnel fdbs present. 

#### Previous command output (if the output of a command-line utility has changed)

root@sonic:~# show mac
  No.    Vlan  MacAddress         Port        Type
-----  ------  -----------------  ----------  -------
    1      77  0C:48:C6:C3:30:F8  Ethernet24  Dynamic
Total number of entries 1
root@sonic:~#

#### New command output (if the output of a command-line utility has changed)

root@sonic:~# show mac
  No.    Vlan  MacAddress         Port        Type
-----  ------  -----------------  ----------  -------
    1      30  72:E5:BE:90:A6:1C  1.1.1.1     Static
    2      30  F6:2C:C6:50:FF:F2  1.1.1.1     Static
    3      30  B2:14:7E:B4:05:3C  1.1.1.1     Static
    4      77  0C:48:C6:C3:30:F8  Ethernet24  Dynamic
Total number of entries 4
root@sonic:~#

2023-01-06 20:50 UTC, prsunny reviewed
looks good, please add unit tests

2023-01-06 21:11 UTC, dgsudharsan requested changes
The remote MACs are supposed to be displayed through the command show vxlan remotemac as per behavior today.
"show mac" command displays only local mac. Why do we need to change show mac?
@srj102 @adyeung  Can someone from Broadcom please provide feedback?

2023-01-09 05:56 UTC, praveenraja1 commented
> show vxlan remotemac



> The remote MACs are supposed to be displayed through the command show vxlan remotemac as per behavior today. "show mac" command displays only local mac. Why do we need to change show mac? @srj102 @adyeung Can someone from Broadcom please provide feedback?

Thanks for the info, i do see that 'show vxlan remotemac' displays all the macs learnt on vxlan tunnel. Will wait for the reply from Broadcom and then discard this review if this is not required.

2023-01-09 06:58 UTC, srj102 commented
currently show vxlan remotemac displays all the MACs from the VXLAN_FDB APP DB table. 

There is no command which gives a global view of all the macs learnt on the switch. 
This enhancement helps with the global view. 

we could also add an option to display only the local macs, 
show mac -local.

2023-01-11 08:05 UTC, praveenraja1 commented
> currently show vxlan remotemac displays all the MACs from the VXLAN_FDB APP DB table.
> 
> There is no command which gives a global view of all the macs learnt on the switch. This enhancement helps with the global view.
> 
> we could also add an option to display only the local macs, show mac -local.

Added this option as requested. 
[Show_fdb_test.txt](https://github.com/sonic-net/sonic-utilities/files/10390019/Show_fdb_test.txt)

2023-06-29 18:26 UTC, maipbui commented
@praveenraja1 Please merge latest master code to trigger Semgrep checker.

2026-09-05 06:41 UTC, closed without merging