[config]: Dynamically start and stop ndppd
sonic-net/sonic-utilities pull request #2814
Opened 2023-05-01 21:49 UTC by theasianpianist

Fixes https://github.com/sonic-net/sonic-buildimage/issues/14231

#### What I did
- When enabling proxy_arp for a VLAN, configure and start the ndppd service if it isn't already running
- When removing the last VLAN, stop the ndppd service

#### How I did it
Check `supervisorctl status ndppd` to determine if ndppd needs to be started or stopped

#### How to verify it
- Load a config on a device that does not have any VLANs
- Create a vlan and enable proxy_arp:
```
sudo config vlan add 10
sudo config interface ip add Vlan10 4.0.0.2/24
sudo config vlan proxy_arp 10 enabled
```
- Verify that the commands succeed and ndppd is running:
```
admin@sonic:~$ docker exec -it swss supervisorctl status ndppd
ndppd                            RUNNING   pid 1744, uptime 0:00:03
```

- Remove the vlan:
```
sudo config interface ip remove Vlan10 4.0.0.2/24
sudo config vlan del 10
```
- Verify that the commands succeed and ndppd is no longer configured:
```
admin@sonic:~$ docker exec -it swss supervisorctl status ndppd
ndppd: ERROR (no such process)
```
#### Previous command output (if the output of a command-line utility has changed)
```
admin@sonic:~$ sudo config vlan proxy_arp 10 enabled
Proxy ARP setting saved to ConfigDB
Running command: docker exec -i swss sonic-cfggen -d -t /usr/share/sonic/templates/ndppd.conf.j2,/etc/ndppd.conf
Running command: docker exec -i swss supervisorctl restart ndppd
ndppd: stopped
ndppd: started
```
```
admin@sonic:~$ sudo config vlan del 10
```

#### New command output (if the output of a command-line utility has changed)
```
admin@sonic:~$ sudo config vlan proxy_arp 10 enabled
Proxy ARP setting saved to ConfigDB
Starting ndppd service
```
```
admin@sonic:~$ sudo config vlan del 10
No VLANs remaining, stopping ndppd service
```

2023-05-02 03:04 UTC, dgsudharsan requested changes
@theasianpianist Can you please add UT for coverage? Other than that changes look good.

2023-05-02 21:16 UTC, dgsudharsan approved these changes

2023-05-02 22:51 UTC, prsunny submitted a review, later dismissed
lgtm, since its marked for 202205, can you confirm the changes are working for 202205 target branch?

2023-05-03 23:26 UTC, prsunny approved these changes

2023-05-03 23:30 UTC, dgsudharsan approved these changes

2023-05-04 17:55 UTC, merged