[202211][db_migrator] Add migration of FLEX_COUNTER_DELAY_STATUS during 1911->2211 upgrade + fast-reboot. Add UT.
sonic-net/sonic-utilities pull request #2838
Opened 2023-05-16 11:29 UTC by vadymhlushko-mlnx

#### What I did
Add migration of `FLEX_COUNTER_DELAY_STATUS` attribute of config_db `FLEX_COUNTER_TABLE` during the `SONiC to SONiC upgrade + fast-reboot` from older versions `201911 -> 202211`.

This change is required for the `fast-reboot` procedure because without it the counters will be created during the init flow which will waste a lot of resources and cause data plane degradation of more than 30 seconds.

#### How I did it
Modify the `db_migrator.py`.

#### How to verify it
Add UT.

#### Previous command output (if the output of a command-line utility has changed)

#### New command output (if the output of a command-line utility has changed)

2023-05-16 11:41 UTC, stepanblyschak approved these changes

2023-05-30 10:14 UTC, stepanblyschak approved these changes

2023-05-31 08:20 UTC, keboliu commented
@vaibhavhd  would you please help to review?

2023-06-13 09:56 UTC, vadymhlushko-mlnx commented on scripts/db_migrator.py
> +            self.migrate_config_db_flex_counter_delay_status()
Resolved

2023-06-15 20:29 UTC, vaibhavhd commented
Why is this change not needed on master?

2023-06-15 20:29 UTC, vaibhavhd approved these changes

2023-06-19 08:15 UTC, keboliu commented
@vadymhlushko-mlnx please resolve the checker issue so we can proceed.

2023-06-19 09:32 UTC, vadymhlushko-mlnx commented
> Why is this change not needed on master?

The PR's for other branches have already been created:

https://github.com/sonic-net/sonic-utilities/pull/2839
https://github.com/sonic-net/sonic-utilities/pull/2870
https://github.com/sonic-net/sonic-utilities/pull/2869

2023-07-03 09:58 UTC, keboliu commented
@StormLiangMS this PR is ready to be merged, would you please help?

2023-07-06 19:44 UTC, vaibhavhd requested changes
The version on 202211 and 202205 is same, this needs to be corrected. Blocking merge of this change until that.

2023-07-06 19:45 UTC, vaibhavhd commented on scripts/db_migrator.py
> +            self.migrate_config_db_flex_counter_delay_status()
Why is this resolved?

2023-07-11 13:49 UTC, vadymhlushko-mlnx commented
> The version on 202211 and 202205 is same, this needs to be corrected. Blocking merge of this change until that.

I've changed the version to `version_4_0_3` which is the same as for `master`. Is it correct, if not could you please explain how to determine the correct version?

2023-07-11 14:10 UTC, vadymhlushko-mlnx commented
> The version on 202211 and 202205 is same, this needs to be corrected. Blocking merge of this change until that.

I've added a placeholder for the `version_3_0_7`. Could you please take a look?

2023-07-18 17:15 UTC, vadymhlushko-mlnx commented
> > The version on 202211 and 202205 is same, this needs to be corrected. Blocking merge of this change until that.
> 
> I've added a placeholder for the `version_3_0_7` which is the same as for the `202205` branch. Could you please tell me if it is correct, if no could you please explain the logic behind defining proper DB migration version per branch?

@vaibhavhd kind reminder

2023-08-17 16:48 UTC, vaibhavhd approved these changes

2023-08-17 17:17 UTC, merged