Additional check to skip FRR-Offloaded check if the bgp route-src was not selected as best
sonic-net/sonic-utilities pull request #3130
Opened 2024-01-23 02:20 UTC by deepak-singhal0408

#### What I did
Fixes https://github.com/sonic-net/sonic-buildimage/issues/17877
#### How I did it
Added additional check to skip FRR-Offloaded check if the routeSrc BGP was not selected as best.
#### How to verify it
Ran the script on multi-asic KVM device, and could confirm the route_check is passing.

#### Previous command output (if the output of a command-line utility has changed)

#### New command output (if the output of a command-line utility has changed)

2024-01-23 02:22 UTC, deepak-singhal0408 commented
@stepanblyschak for viz.

2024-01-25 22:40 UTC, stepanblyschak requested changes
LGTM, but fix indent with spaces

2024-01-25 22:40 UTC, stepanblyschak commented on scripts/route_check.py
> +		# skip if this bgp source prefix is not selected as best
Replace tabs with spaces

2024-01-25 23:02 UTC, stepanblyschak approved these changes

2024-01-25 23:23 UTC, deepak-singhal0408 commented
@qiluo-msft, @prsunny can you please help merge? Thanks!

2024-01-26 23:15 UTC, prsunny approved these changes

2024-01-27 16:17 UTC, merged