Revert "Optimize techsupport reducing number of vtysh calls in scale sceario"
sonic-net/sonic-utilities pull request #3694
Opened 2024-12-21 04:45 UTC by xwjiang-ms

Reverts sonic-net/sonic-utilities#3605 for it's causing PR test failure:
```
=================================== FAILURES ===================================
______________________ test_techsupport_commands[vlab-01] ______________________

duthosts = [<MultiAsicSonicHost vlab-01>]
enum_rand_one_per_hwsku_frontend_hostname = 'vlab-01'
commands_to_check = {'bfd_cmds': ["vtysh -c 'show bfd peers'", "vtysh -c 'show bfd peers counters'", "vtysh -c 'show bfd peers json'", "vt... ['/proc/buddyinfo', '/proc/cmdline', '/proc/consoles', '/proc/cpuinfo', '/proc/devices', '/proc/diskstats', ...], ...}
skip_on_dpu = None

    def test_techsupport_commands(
            duthosts, enum_rand_one_per_hwsku_frontend_hostname, commands_to_check, skip_on_dpu):  # noqa F811
        """
        This test checks list of commands that will be run when executing
        'show techsupport' CLI against a standard expected list of commands
        to run.
    
        The test invokes show techsupport with noop option, which just
        returns the list of commands that will be run when collecting
        tech support data.
    
        Args:
        commands_to_check: contains a dict of command groups with each
        group containing a list of related commands.
        """
    
        cmd_not_found = defaultdict(list)
        duthost = duthosts[enum_rand_one_per_hwsku_frontend_hostname]
    
        stdout = duthost.shell(r'sudo generate_dump -n | grep -v "^mkdir\|^rm\|^tar\|^gzip"')
    
        pytest_assert(stdout['rc'] == 0, 'generate_dump command failed')
    
        cmd_list = stdout["stdout_lines"]
    
        strbash_in_cmdlist = False
        for command in cmd_list:
            if "bash -c" in command:
                strbash_in_cmdlist = True
                break
    
        for cmd_group_name, cmd_group_to_check in list(commands_to_check.items()):
            cmd_not_found.update(
                check_cmds(cmd_group_name, cmd_group_to_check, cmd_list, strbash_in_cmdlist)
            )
    
        error_message = ''
        for key, commands in cmd_not_found.items():
            error_message += "Commands not found for '{}': ".format(key) + '; '.join(commands) + '\n'
    
>       pytest_assert(len(cmd_not_found) == 0, error_message)
E       Failed: Commands not found for 'bgp_cmds': vtysh\s+-c "show ip bgp neighbors .* advertised-routes"; vtysh\s+-c "show ip bgp neighbors .* routes"; vtysh\s+-c "show bgp ipv6 neighbors .* advertised-routes"; vtysh\s+-c "show bgp ipv6 neighbors .* routes"

cmd_group_name = 'docker_cmds'
cmd_group_to_check = ['docker exec syncd saidump', 'docker stats --no-stream', 'docker ps -a', 'docker top pmon', 'docker exec lldp lldpcli show statistics', 'docker logs bgp', ...]
cmd_list   = ['Lock succesfully accquired and installed signal handlers', 'touch --date=@0 /tmp/reference', 'ln -s /usr/local/bin/g...ump_vlab-01_20241220_065209/proc', 'echo cp  -r /proc/consoles /var/dump/sonic_dump_vlab-01_20241220_065209/proc', ...]
cmd_not_found = defaultdict(<class 'list'>, {'bgp_cmds': ['vtysh\\s+-c "show ip bgp neighbors .* advertised-routes"', 'vtysh\\s+-c "sh...s"', 'vtysh\\s+-c "show bgp ipv6 neighbors .* advertised-routes"', 'vtysh\\s+-c "show bgp ipv6 neighbors .* routes"']})
command    = 'timeout --foreground 5m bash -c "dummy_cleanup_method () '
commands   = ['vtysh\\s+-c "show ip bgp neighbors .* advertised-routes"', 'vtysh\\s+-c "show ip bgp neighbors .* routes"', 'vtysh\\s+-c "show bgp ipv6 neighbors .* advertised-routes"', 'vtysh\\s+-c "show bgp ipv6 neighbors .* routes"']
commands_to_check = {'bfd_cmds': ["vtysh -c 'show bfd peers'", "vtysh -c 'show bfd peers counters'", "vtysh -c 'show bfd peers json'", "vt... ['/proc/buddyinfo', '/proc/cmdline', '/proc/consoles', '/proc/cpuinfo', '/proc/devices', '/proc/diskstats', ...], ...}
duthost    = <MultiAsicSonicHost vlab-01>
duthosts   = [<MultiAsicSonicHost vlab-01>]
enum_rand_one_per_hwsku_frontend_hostname = 'vlab-01'
error_message = 'Commands not found for \'bgp_cmds\': vtysh\\s+-c "show ip bgp neighbors .* advertised-routes"; vtysh\\s+-c "show ip b...routes"; vtysh\\s+-c "show bgp ipv6 neighbors .* advertised-routes"; vtysh\\s+-c "show bgp ipv6 neighbors .* routes"\n'
key        = 'bgp_cmds'
skip_on_dpu = None
stdout     = {'changed': True, 'stdout': 'Lock succesfully accquired and installed signal handlers\ntouch --date=@0 /tmp/reference\...or directory', 'ERR: RC:-1 observed on line 2250', 'Removing lock. Exit: 0'], '_ansible_no_log': None, 'failed': False}
strbash_in_cmdlist = True
```

2024-12-21 04:45 UTC, mssonicbld commented
/azp run

2024-12-21 07:46 UTC, xwjiang-ms commented
Created test PR to try if PR test could pass after reverting https://github.com/sonic-net/sonic-utilities/pull/3605

2024-12-21 17:34 UTC, dgsudharsan commented
No need to revert this. I created a sonic-mgmt PR https://github.com/sonic-net/sonic-mgmt/pull/16195. This might be due to circular dependency as the sonic-mgmt https://github.com/sonic-net/sonic-mgmt/pull/15466 contains the fix but cannot be merged until sonic-utilities submodule is updated. In order overcome this I created a temporary PR removing the commands that cause failure and then once submodule is updated we can merge https://github.com/sonic-net/sonic-mgmt/pull/15466

2024-12-21 17:46 UTC, dgsudharsan requested changes
As mentioned please check my comments in PR. I already created a temporary PR to overcome customer dependecy

2024-12-22 09:16 UTC, xwjiang-ms commented
@dgsudharsan Good to see your fix, will close this revert PR

2024-12-22 09:16 UTC, closed without merging